name: Deploy Cloud Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      hello_world_changed: ${{ steps.filter.outputs.hello_world }}
      greeting_changed: ${{ steps.filter.outputs.greeting }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            hello_world:
              - 'functions/hello_world/**'
            greeting:
              - 'functions/greeting/**'

  deploy-hello-world:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.hello_world_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Hello World Function
        run: |
          gcloud builds submit --config functions/hello_world/deploy.yaml

  deploy-greeting:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.greeting_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Greeting Function
        run: |
          gcloud builds submit --config functions/greeting/deploy.yaml 